name: Hello World Workflow
on: 
  push:
    branches:
      - master
jobs: 
    say-hello:
        runs-on: ubuntu-latest
        env:
          GREETING: "G'day from Sydney"
          MY_NAME: "Faiaz"
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v6
            - name: print hello
              run: echo "hello from github actions!"
            - name: show current date 
              run: date
            - name: list repo files
              run: ls -la
            - name: greet by name
              run: echo "$GREETING, $MY_NAME!"